---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-secret
  namespace: taskapp
spec:
  encryptedData:
    JWT_SECRET_KEY: AgBu+lSxGEaSXCoxZbi8tSNlvfblJLagzUc9cksp8KRV4A1Ch/3aSi0fydLXS096owCUa+JFjmkDoQo7ZsL4HzUAUR3lpwN6zxQWKk59NhHLGB+FucLLySrKmod+1jlr51Wqg7OzP4XHYJByeZ2Z3RtU3QxnmqJB9f33WIIv/GrQXHWAqCPdsi/gn9CKKbaZwMhhA6UaKIZYASHZjFJZLh+eKsge8uJGapPViwj0u8083vjTnHFnaZrZOA4KeaM9pExy2j+KdcnP6MTonr58VrlDrLr9eYms5ETqqRbxaxmQdds4QcH3A9SxO4Usdg3dkYBazKKFNIiq9SrBx4xfFpyJWb0NsTYMXyn9ggZDc8plFSJevCVXM/J0gCLpCVxV+LFCvOBV3VR1y61HZpfLAnZ1n7b47WIBsXG5o8ckZssutcSGza3rnedZYMniWbwpT7H74YPER0WEPL1kAaZLHSXOpaiF1VhZtBV927ohh3Kin14YO9WoI2QQQ7FAII/emWhDzycqp81m5qaRm+kvkPSJeWBhODgqJyPU4EbrhkFdnxN46aCJXzUconL6xsUuW2TkBJf7CeVJunQZ825jBnQygLfbDRBGpWT1fCbkpiPHXXpVr4UDFye042QSMDNjQxT9Uu0jN10u0jWpIGSCyevtJ63lkgKMp37QXaKXvjjcsZAJX2+hQmUCIg8uf7Qfgcwu5jUAALijxMUDq1Qhc1hWFK4/0lbUuYRwSmdaGdPqWDDbqiflF/F83Q==
  template:
    metadata:
      name: backend-secret
      namespace: taskapp
