---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-secret
  namespace: taskapp
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBcNmn+gF5YDNu01p/HPYzon2yRRIg26a2+3lH87zZ+XosKzhD5x6hrynE6L5mJka6R1c0R/SiT71gauUsp0PLmnPwFfhmbdzby9SVIMfyaUu8eDHZ39HOvtQ+v1q9ASoIW8nfVC6UJPqBfA0Ewkdx+cy8+v3lzlcFR/FeL9ajpz+jDzccHqcDWMPhD0nO4c3X5xZOJ5xD/cyUSDPogmTuNs+NQJuZKBq0sMPvsm1BrXb/JJWOzgkisCkBF77kvfv5hsJXgQLMHOEz40AkBmE6CEFZMdIQ5NtnMoNTbH58Z+B35DalyNEyZKZK9oz8Eas43X8t12TdAkd8Ld0SwqS5XpTu7vCHNy4lyzfzh6WdMp/a7+ioTIdnSx4r1iSLCjVODa5LKJyATS6jGWXfftwOAT63zEyIkSKX+3egNOo4SEjYhU0DSYnbvReDchXdbdK5pf/JgYiChtNWa0/YwryC6vsjwB+7wJ6wKn162OkHPAw/CWyagNnEqqeS4oit+F2MAe78+hVCv1jr+ibN+9XX+B6AZedibGfGw4yuYaUeWFl1YQ2ppwITwl2fM/G5fb3dJ7x2BR6Pw7w1TkipgrobxQ3BXEM+jcsMeSDU17gFlTqwgq7On7aYyBF3TRty9HWTlkc8xKY93J04xm0bQQOMA9aUkefpxgvfZFNOC9K5lGFYVI1zxGd+sj9+5ZpF/JPFNAoWpcj/PNjOHGoublvDyEB7cDMe8bbvXvA==
    POSTGRES_USER: AgAPXkDMKoZoqpa3pBLjCWsunmVBrJ+L8M4axWOJy3zHOEH/fp7FMmUjHXQ8en/anaQdlIvKYpw33QCQFZfi/JOVFpehagWltj4b0d/dlezfN1dq3+O8/KtylNcRgHqnrRqQ02uN+TnXhIR1SQUUfYV3zrkKbyynoQ1X2RgFcCOYeU3OnXLvLy+/ueU8Ba/T/DpdrHRqClTp1pNBnTTqKhhAXLF60crBnFRXCQCx1wjb2AgfNjKuVdq5pwpf0se2P+vgg5K5GyuuSg+yk7T3Nz6o71eggH5bXd5EqhNsvYH+kWEchkYc8A8Uq5rlxK95KQB/Fr9cvjKjqzyaYQEPNf8seUN/rw5Fxz9GzNTzxxsbqkazQ7oSOPll8YsTCV7fHXbz3LhB55AJAV3Pr1IWXRLuuXA2o+ne+44wQyxoKHt/tgFRbb2j1vuN42Xik/vjIn6BhXx2BmuaKzs5zoLYkT/y5+MdGISoxKTslWgYopuHhqufkNyXrx7BGxnOrUaOBfdljqm3sTcroUbrHPDBOmDRDHbwTJAhT8+k3sQn5oiSmnlI+TKoQmitbngt8576rqN0F7gxQAGxyZ34wDf/WXwYT3CZYTF9i5wcb2CozBG3cKzsAc1b40BdSELd5+T0MJgfI7jNd16iLT+RdFaDNDpUz7kPw7CC/o/376u3EnL1S3ko9ym2ujkQUVy26iQTb7FiaK0M3vnt
  template:
    metadata:
      name: db-secret
      namespace: taskapp
